### ISSUE TITLE
Some improvements for the bot

### ISSUE THREAD

**Issue by LeonardoNhemetz** [miquelt9/otaniemitrackerbot#7]
**At a priority level:**

- [1] Consider breaking down the code into smaller functions or classes. This will make the code more modular and easier to understand.
- [2] Review and clean up the code to remove redundant or unused code and dependencies.
- [3] Review the code for potential security vulnerabilities. For example, ensure that user inputs are properly sanitized to prevent code injection attacks.
- [4] Incorporate logging to keep track of bot activities, errors, and user interactions. Logging is essential for debugging and monitoring.

**Comment by miquelt9** [comment]
Overall improvements were made to the bot on this commit https://github.com/miquelt9/otaniemitrackerbot/commit/cc3ec5b5311a9031ae219c3fd83b317b93790a92, thanks for your comment Leonardo.

I do close it now but if you see any other thing, please don't hesitate to open an issue again :)
